### ISSUE TITLE
Transition from Rational to HalfInteger

### ISSUE THREAD

**Issue by jagot** [JuliaAtoms/AtomicLevels.jl#7]
In many places, `Rational`s are being used for angular momenta. These can be more efficiently represented by `HalfInteger` [from WignerSymbols.jl](https://github.com/Jutho/WignerSymbols.jl/blob/master/src/halfinteger.jl). E.g `Term` would simply be
```julia
struct Term
    L::HalfInteger
    S::HalfInteger
    parity::Parity
end
```

**Comment by jagot** [comment]
We should also ask @Jutho to export the `HalfInteger` interface.

**Comment by Jutho** [comment]
You mean a simple `export HalfInteger` in WignerSymbols.jl? I am certainly fine with that.

**Comment by mortenpi** [comment]
Would you also consider some minor API additions? I have a version of your `HalfInteger` with some updates in [one of the PRs](https://github.com/JuliaAtoms/AtomicLevels.jl/pull/10/files#diff-a2561d67a642b3062a53aadecca6535e). I would be more than happy to prepare a PR against WignerSymbols.

* It is mainly just a few additional methods, such as multiplication with integers and string parsing.
* I also found it handy to have a `HalfIntegerRange` type, mirroring `UnitRange`, so that you could write e.g. `HalfInteger(-10) : HalfInteger(10)`. Not sure if that is appropriate for WignerSymbols.
* If I may, I might also suggest a small change to how the constructor behaves. I find it more intuitive if `HalfInteger(n) == n` not `HalfInteger(n) == n // 2`.

**Comment by Jutho** [comment]
Yes I am open to such changes and would probably benefit from them as well. The most Julian choice for the constructor was also something I was wondering about.
